const translations = {
  en: {
    "nav.experience": "Experience",
    "nav.research": "Research",
    "nav.projects": "Projects",
    "nav.skills": "Skills",
    "nav.contact": "Contact",
    "hero.tag": "Available for new opportunities",
    "hero.title": "AI Solutions &amp; Systems Engineer",
    "hero.desc": "Research Assistant at GWDG contributing to the KISSKI AI Service Center. I bridge the gap between High-Performance Computing (HPC) and customer-facing AI solutions through secure, private infrastructure.",
    "hero.cta": "Get in touch",
    "exp.label": "// Work History",
    "exp.heading": "Experience",
    "exp.gwdg.role": "Research Assistant",
    "exp.gwdg.li1": "KISSKI Project: Architected and deployed production-grade AI services using Kubernetes and Istio on secure GWDG hardware.",
    "exp.gwdg.li2": "Customer Integration: Developed end-user prototypes for Chat-AI, including image generation, audio transcription, and long-term memory recognition.",
    "exp.gwdg.li3": "Enhanced Chat-AI scheduler, added health checks for HPC AI model jobs",
    "exp.gwdg.li4": "Infrastructure Optimization: Introduced scale-to-zero GPU management to optimize private AI model deployment for sensitive use cases.",
    "exp.gwdg.li5": "Reliability Engineering: Implemented automatic validation of clusters to ensure high availability for research services.",
    "exp.gwdg.li6": "Improved system reliability by validating configurations against schema (Ironik project)",
    "exp.gwdg.li7": "Terminal AI Integration: Developed the “Gofer” tool for accessing Chat-AI via terminal APIs, including Slurm job monitoring, file access, and a chat module with model selection.",
    "exp.dm360.role": "Werkstudent Python Developer",
    "exp.dm360.li1": "Backend development with Python; behavior testing &amp; CI/CD with Jira &amp; GitLab",
    "exp.dm360.li2": "Developed automated PowerShell scripts and web scrapers using BeautifulSoup &amp; Selenium",
    "exp.dm360.li3": "Built and maintained custom Conda packages",
    "exp.fhg.role": "Student Assistant",
    "exp.fhg.li1": "Developed interactive dashboards using Python/Holoviz (param &amp; panel)",
    "exp.fhg.li2": "Built tooling to generate microcontroller bit files &amp; programming via UniFlash/J-Link",
    "exp.fhg.li3": "Python unit testing with pytest; CI/CD integration with GitLab",
    "exp.alpyog.role": "E-Commerce Functional Executive",
    "exp.alpyog.li1": "Built web scraper integrated with Google Sheets via Cloud API",
    "exp.alpyog.li2": "Automated inventory management — data retrieval, validation &amp; form-filling from CSV",
    "exp.alpyog.li3": "Developed REST APIs &amp; image processing utilities in Python; Google App Script in JS",
    "thesis.label": "// Research",
    "thesis.heading": "Master's Thesis",
    "thesis.title": "Benchmarking Network Acceleration in Kubernetes Clusters<br>with 2nd Gen NVIDIA BlueField DPUs",
    "thesis.desc": "Comprehensive performance analysis of DOCA SDK containerized applications on BlueField-2 DPUs, comparing Virtual Function vs Physical Function access modes across latency, throughput, horizontal scaling, and CPU overhead in a dual-node ARM server environment.",
    "thesis.m1": "Latency improvement via hardware acceleration",
    "thesis.m2": "Throughput at 5 replicas with near-perfect efficiency",
    "thesis.m3": "CPU overhead reduction through DPU offloading",
    "thesis.repo": "↗ View Repository",
    "proj.label": "// Side Projects",
    "proj.heading": "Projects",
    "proj.chatai.title": "Job Scraper and Chat-AI API Integration",
    "proj.chatai.desc": "Developed a job description scraper to extract data from various sources and integrated it with the Chat-AI API for CV comparison.",
    "proj.flipkart.title": "Flipkart Web Scraper",
    "proj.flipkart.desc": "Data scraping tool for e-commerce product data — titles, prices, ratings, reviews — exported to CSV. Built with BeautifulSoup and a Tkinter UI.",
    "proj.books.title": "Online Secondhand Bookstore",
    "proj.books.desc": "Full-stack Django web app for selling used books with user auth, book search, order ratings, session management, and REST API integration.",
    "skills.label": "// Technical Stack",
    "skills.heading": "Skills",
    "skills.cloud": "Cloud &amp; Infrastructure",
    "skills.languages": "Languages",
    "skills.hpc": "HPC &amp; Systems",
    "skills.data": "Data &amp; ML Tooling",
    "skills.devops": "DevOps &amp; CI/CD",
    "skills.web": "Web &amp; Backend",
    "contact.label": "// Get In Touch",
    "contact.heading": "Let's work<br>together.",
    "contact.desc": "Open to full-time roles in systems engineering, cloud infrastructure, or research-oriented positions. Based in Göttingen, Germany — open to remote.",
    "contact.cta": "Send an Email →",
    "footer.text": "Siddharth Simediya — Systems Engineer &amp; Researcher · Göttingen, Germany"
  },
  de: {
    "nav.experience": "Erfahrung",
    "nav.research": "Forschung",
    "nav.projects": "Projekte",
    "nav.skills": "Kenntnisse",
    "nav.contact": "Kontakt",
    "hero.tag": "Offen für neue Möglichkeiten",
    "hero.title": "KI-Lösungen &amp; Systemingenieur",
    "hero.desc": "Wissenschaftlicher Mitarbeiter bei der GWDG im KISSKI KI-Servicezentrum. Ich verbinde Hochleistungsrechnen (HPC) mit nutzerorientierten KI-Lösungen über sichere, private Infrastruktur.",
    "hero.cta": "Kontakt aufnehmen",
    "exp.label": "// Berufserfahrung",
    "exp.heading": "Erfahrung",
    "exp.gwdg.role": "Wissenschaftlicher Mitarbeiter",
    "exp.gwdg.li1": "KISSKI-Projekt: Architektur und Bereitstellung produktionsreifer KI-Dienste mit Kubernetes und Istio auf sicherer GWDG-Hardware.",
    "exp.gwdg.li2": "Kundenintegration: Entwicklung von Prototypen für Endnutzer mit Chat-AI, inklusive Bildgenerierung, Audiotranskription und Langzeitgedächtnis.",
    "exp.gwdg.li3": "Verbesserung des Chat-AI-Schedulers und Hinzufügen von Health Checks für HPC-KI-Modelljobs.",
    "exp.gwdg.li4": "Infrastrukturoptimierung: Einführung von Scale-to-Zero-GPU-Management für private KI-Modelle in sensiblen Anwendungsfällen.",
    "exp.gwdg.li5": "Reliability Engineering: Implementierung einer automatischen Cluster-Validierung, um eine hohe Verfügbarkeit für Forschungsdienste sicherzustellen.",
    "exp.gwdg.li6": "Verbesserung der Systemzuverlässigkeit durch schema-basierte Konfigurationsvalidierung (Ironik-Projekt).",
    "exp.gwdg.li7": "Terminal AI Integration: Entwicklung des „Gofer“-Tools zur Nutzung von Chat-KI über APIs im Terminal, inkl. Slurm-Job-Monitoring, Dateizugriff und Chat-Modul mit Modellauswahl.",
    "exp.dm360.role": "Werkstudent Python-Entwickler",
    "exp.dm360.li1": "Backend-Entwicklung mit Python; Verhaltenstests sowie CI/CD mit Jira und GitLab.",
    "exp.dm360.li2": "Entwicklung von automatisierten PowerShell-Skripten und Web-Scrapern mit BeautifulSoup und Selenium.",
    "exp.dm360.li3": "Erstellung und Pflege von benutzerdefinierten Conda-Paketen.",
    "exp.fhg.role": "Studentische Hilfskraft",
    "exp.fhg.li1": "Entwicklung interaktiver Dashboards mit Python/Holoviz (param &amp; panel)",
    "exp.fhg.li2": "Erstellung eines interaktiven Dashboards zur Anzeige von Mikrocontroller-Bit-Dateien",
    "exp.fhg.li3": "Python-Unit-Tests mit pytest; CI/CD-Integration mit GitLab",
    "exp.alpyog.role": "E-Commerce Funktionsleiter",
    "exp.alpyog.li1": "Web-Scraper mit Google Sheets-Integration über Cloud API entwickelt",
    "exp.alpyog.li2": "Lagerverwaltung automatisiert — Datenabruf, Validierung &amp; Formularausfüllung aus CSV",
    "exp.alpyog.li3": "REST-APIs &amp; Bildverarbeitungs-Utilities in Python entwickelt; Google App Script in JS",
    "thesis.label": "// Forschung",
    "thesis.heading": "Masterarbeit",
    "thesis.title": "Benchmarking der Netzwerkbeschleunigung in Kubernetes-Clustern<br>mit NVIDIA BlueField DPUs der 2. Generation",
    "thesis.desc": "Umfassende Leistungsanalyse containerisierter DOCA-SDK-Anwendungen auf BlueField-2 DPUs, Vergleich von Virtual Function vs. Physical Function Zugriffsmodi hinsichtlich Latenz, Durchsatz, horizontaler Skalierung und CPU-Overhead in einer Dual-Node ARM-Serverumgebung.",
    "thesis.m1": "Latenzverbesserung durch Hardware-Beschleunigung",
    "thesis.m2": "Durchsatz bei 5 Replikaten mit nahezu perfekter Effizienz",
    "thesis.m3": "CPU-Overhead-Reduktion durch DPU-Offloading",
    "thesis.repo": "↗ Repository ansehen",
    "proj.label": "// Nebenprojekte",
    "proj.heading": "Projekte",
    "proj.chatai.title": "Job Scraper und Chat-AI API-Integration",
    "proj.chatai.desc": "Einen Scraper für Stellenbeschreibungen entwickelt, um Daten aus verschiedenen Quellen zu extrahieren, und diesen zur Vergleichung von Lebensläufen in die Chat-AI-API integriert.",
    "proj.flipkart.title": "Flipkart Web-Scraper",
    "proj.flipkart.desc": "Datenabruf-Tool für E-Commerce-Produktdaten — Titel, Preise, Bewertungen, Rezensionen — als CSV exportiert. Entwickelt mit BeautifulSoup und Tkinter UI.",
    "proj.books.title": "Online-Gebrauchtbuchladen",
    "proj.books.desc": "Full-Stack Django-Webanwendung für den Verkauf gebrauchter Bücher mit Nutzerauthentifizierung, Buchsuche, Bestellbewertungen, Session-Management und REST-API-Integration.",
    "skills.label": "// Tech-Stack",
    "skills.heading": "Kenntnisse",
    "skills.cloud": "Cloud &amp; Infrastruktur",
    "skills.languages": "Programmiersprachen",
    "skills.hpc": "HPC &amp; Systeme",
    "skills.data": "Daten &amp; ML-Werkzeuge",
    "skills.devops": "DevOps &amp; CI/CD",
    "skills.web": "Web &amp; Backend",
    "contact.label": "// Kontakt aufnehmen",
    "contact.heading": "Lass uns zusammen<br>arbeiten.",
    "contact.desc": "Offen für Vollzeitstellen in Systems Engineering, Cloud-Infrastruktur oder forschungsnahen Positionen. Wohnhaft in Göttingen — remote möglich.",
    "contact.cta": "E-Mail senden →",
    "footer.text": "Siddharth Simediya — Systemingenieur &amp; Forscher · Göttingen, Deutschland"
  }
};

function setLang(lang) {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang] && translations[lang][key] !== undefined) {
      el.innerHTML = translations[lang][key];
    }
  });
  document.getElementById('btn-en').classList.toggle('active', lang === 'en');
  document.getElementById('btn-de').classList.toggle('active', lang === 'de');
  document.documentElement.lang = lang;
  localStorage.setItem('lang', lang);
}

// Restore saved language preference
(function() {
  const saved = localStorage.getItem('lang');
  if (saved && saved !== 'en') setLang(saved);
})();
