const translations = {
  en: {
    "nav.experience": "Experience",
    "nav.research": "Research",
    "nav.education": "Education",
    "nav.projects": "Projects",
    "nav.skills": "Skills",
    "nav.contact": "Contact",
    "hero.tag": "Available for new opportunities",
    "hero.title": "AI Automation &amp; Integration Engineer",
    "hero.desc": "Engineer with hands-on experience integrating AI capabilities into production systems and building API-driven automation — from GWDG's AI chat platform to a self-built FastAPI booking platform with TOTP-based authentication. I automate workflows with Python, model business rules directly into validation logic, and ship changes through CI/CD pipelines and Docker.",
    "hero.cta": "Get in touch",
    "exp.label": "// Work History",
    "exp.heading": "Experience",
    "exp.gwdg.role": "Research Assistant",
    "exp.gwdg.li2": "Customer Integration: Integrated image generation, audio transcription, and memory functions into the Chat-AI platform.",
    "exp.gwdg.li3": "Implemented health-check mechanisms for AI models on HPC systems and optimized the job scheduler to prevent system crashes.",
    "exp.gwdg.li4": "Infrastructure Optimization: Introduced a scale-to-zero GPU management approach, balancing cost against availability for private AI deployments.",
    "exp.gwdg.li5": "Built monitoring and observability tooling across all projects using Prometheus and Grafana.",
    "exp.gwdg.li6": "Ironik project: Automated validation of Kubernetes cluster configurations against defined schemas, improving system stability; used Ansible to manage Rancher-based clusters.",
    "exp.gwdg.li7": "Terminal AI Integration: Developed the “Gofer” tool for accessing Chat-AI via terminal APIs, including Slurm job monitoring, file access, and a chat module with model selection.",
    "exp.dm360.role": "Werkstudent Python Developer",
    "exp.dm360.li1": "Backend development in Python, applying behavior-driven testing (BDD) methods; ran CI workflows with Jira &amp; GitLab",
    "exp.dm360.li2": "Developed automated PowerShell scripts and web scrapers using BeautifulSoup &amp; Selenium",
    "exp.dm360.li3": "Built and maintained custom Conda packages",
    "exp.alpyog.role": "E-Commerce Functional Executive",
    "exp.alpyog.li1": "Built web scraper integrated with Google Sheets via Cloud API",
    "exp.alpyog.li2": "Automated inventory management — data retrieval, validation &amp; form-filling from CSV",
    "exp.alpyog.li3": "Developed REST APIs &amp; image processing utilities in Python; Google App Script in JS",
    "thesis.label": "// Research",
    "thesis.heading": "Master's Thesis",
    "thesis.title": "Benchmarking Network Acceleration in Kubernetes Clusters<br>with 2nd Gen NVIDIA BlueField DPUs",
    "thesis.desc": "Comprehensive performance analysis of DOCA SDK containerized applications on BlueField-2 DPUs, comparing Virtual Function vs Physical Function access modes across latency, throughput, horizontal scaling, and CPU overhead in a dual-node ARM server environment.",
    "thesis.m1": "Latency improvement via hardware acceleration",
    "thesis.m2": "Throughput at 5 replicas with near-perfect efficiency",
    "thesis.m3": "CPU overhead reduction through DPU offloading",
    "thesis.repo": "↗ View Repository",
    "edu.label": "// Education",
    "edu.heading": "Education",
    "edu.msc.degree": "M.Sc. Applied Computer Science",
    "edu.msc.desc": "Thesis: Benchmarking Network Acceleration in Kubernetes Clusters with 2nd Gen NVIDIA BlueField DPUs.",
    "edu.be.degree": "B.E. Information Technology",
    "proj.label": "// Side Projects",
    "proj.heading": "Projects",
    "proj.kinderkreis.title": "Kinderkreis — Childcare Booking Platform",
    "proj.kinderkreis.desc": "Full-stack FastAPI/Pydantic v2 REST API (20 endpoints) for certified childcare booking, with email-OTP user sessions and TOTP-based two-factor admin auth. Regulatory business rules modeled directly into validation, with automatic .ics calendar invites and a 137-test pytest suite, deployed via GitHub Actions CI/CD to Docker Compose.",
    "proj.chatai.title": "Job Scraper and Chat-AI API Integration",
    "proj.chatai.desc": "Developed a job description scraper to extract data from various sources and integrated it with the Chat-AI API for CV comparison.",
    "proj.flipkart.title": "Flipkart Web Scraper",
    "proj.flipkart.desc": "Data scraping tool for e-commerce product data — titles, prices, ratings, reviews — exported to CSV. Built with BeautifulSoup and a Tkinter UI.",
    "proj.books.title": "Online Secondhand Bookstore",
    "proj.books.desc": "Full-stack Django web app for selling used books with user auth, book search, order ratings, session management, and REST API integration.",
    "skills.label": "// Technical Stack",
    "skills.heading": "Skills",
    "skills.cloud": "Cloud &amp; Infrastructure",
    "skills.languages": "Languages",
    "skills.hpc": "HPC &amp; Systems",
    "skills.data": "Data &amp; ML Tooling",
    "skills.devops": "DevOps &amp; CI/CD",
    "skills.web": "Web &amp; Backend",
    "contact.label": "// Get In Touch",
    "contact.heading": "Let's work<br>together.",
    "contact.desc": "Open to full-time roles in systems engineering, cloud infrastructure, or research-oriented positions. Based in Göttingen, Germany — open to remote.",
    "contact.cta": "Send an Email →",
    "footer.text": "Siddharth Simediya — Systems Engineer &amp; Researcher · Göttingen, Germany"
  },
  de: {
    "nav.experience": "Erfahrung",
    "nav.research": "Forschung",
    "nav.education": "Ausbildung",
    "nav.projects": "Projekte",
    "nav.skills": "Kenntnisse",
    "nav.contact": "Kontakt",
    "hero.tag": "Offen für neue Möglichkeiten",
    "hero.title": "KI-Automatisierungs- &amp; Integrationsingenieur",
    "hero.desc": "Ingenieur mit praktischer Erfahrung in der Integration von KI-Funktionen in Produktivsysteme und dem Aufbau API-gesteuerter Automatisierung — von der KI-Chat-Plattform der GWDG bis zu einer selbst entwickelten FastAPI-Buchungsplattform mit TOTP-basierter Authentifizierung. Ich automatisiere Workflows mit Python, bilde Geschäftsregeln direkt in Validierungslogik ab und liefere Änderungen über CI/CD-Pipelines und Docker aus.",
    "hero.cta": "Kontakt aufnehmen",
    "exp.label": "// Berufserfahrung",
    "exp.heading": "Erfahrung",
    "exp.gwdg.role": "Wissenschaftlicher Mitarbeiter",
    "exp.gwdg.li2": "Kundenintegration: Bild-generierung, Audiotranskription und Gedächtnisfunktionen in die Chat-AI-Plattform integriert.",
    "exp.gwdg.li3": "Health-Check-Mechanismen für KI-Modelle auf HPC-Systemen implementiert und den Job-Scheduler optimiert, um Systemabstürze zu verhindern.",
    "exp.gwdg.li4": "Infrastrukturoptimierung: Einführung eines Scale-to-Zero-GPU-Managements zur Abwägung von Kosten und Verfügbarkeit bei privaten KI-Deployments.",
    "exp.gwdg.li5": "Monitoring- und Observability-Tooling für alle Projekte mit Prometheus und Grafana aufgebaut.",
    "exp.gwdg.li6": "Ironik-Projekt: Automatisierte Validierung von Kubernetes-Cluster-Konfigurationen gegen definierte Schemas zur Verbesserung der Systemstabilität; Verwaltung Rancher-basierter Cluster mit Ansible.",
    "exp.gwdg.li7": "Terminal AI Integration: Entwicklung des „Gofer“-Tools zur Nutzung von Chat-KI über APIs im Terminal, inkl. Slurm-Job-Monitoring, Dateizugriff und Chat-Modul mit Modellauswahl.",
    "exp.dm360.role": "Werkstudent Python-Entwickler",
    "exp.dm360.li1": "Backend-Entwicklung mit Python nach Behavior-Driven-Testing (BDD)-Methoden; CI-Workflows mit Jira und GitLab.",
    "exp.dm360.li2": "Entwicklung von automatisierten PowerShell-Skripten und Web-Scrapern mit BeautifulSoup und Selenium.",
    "exp.dm360.li3": "Erstellung und Pflege von benutzerdefinierten Conda-Paketen.",
    "exp.alpyog.role": "E-Commerce Funktionsleiter",
    "exp.alpyog.li1": "Web-Scraper mit Google Sheets-Integration über Cloud API entwickelt",
    "exp.alpyog.li2": "Lagerverwaltung automatisiert — Datenabruf, Validierung &amp; Formularausfüllung aus CSV",
    "exp.alpyog.li3": "REST-APIs &amp; Bildverarbeitungs-Utilities in Python entwickelt; Google App Script in JS",
    "thesis.label": "// Forschung",
    "thesis.heading": "Masterarbeit",
    "thesis.title": "Benchmarking der Netzwerkbeschleunigung in Kubernetes-Clustern<br>mit NVIDIA BlueField DPUs der 2. Generation",
    "thesis.desc": "Umfassende Leistungsanalyse containerisierter DOCA-SDK-Anwendungen auf BlueField-2 DPUs, Vergleich von Virtual Function vs. Physical Function Zugriffsmodi hinsichtlich Latenz, Durchsatz, horizontaler Skalierung und CPU-Overhead in einer Dual-Node ARM-Serverumgebung.",
    "thesis.m1": "Latenzverbesserung durch Hardware-Beschleunigung",
    "thesis.m2": "Durchsatz bei 5 Replikaten mit nahezu perfekter Effizienz",
    "thesis.m3": "CPU-Overhead-Reduktion durch DPU-Offloading",
    "thesis.repo": "↗ Repository ansehen",
    "edu.label": "// Ausbildung",
    "edu.heading": "Ausbildung",
    "edu.msc.degree": "M.Sc. Angewandte Informatik",
    "edu.msc.desc": "Masterarbeit: Benchmarking der Netzwerkbeschleunigung in Kubernetes-Clustern mit NVIDIA BlueField DPUs der 2. Generation.",
    "edu.be.degree": "B.E. Informationstechnologie",
    "proj.label": "// Nebenprojekte",
    "proj.heading": "Projekte",
    "proj.kinderkreis.title": "Kinderkreis — Buchungsplattform für Kinderbetreuung",
    "proj.kinderkreis.desc": "Full-Stack FastAPI/Pydantic-v2-REST-API (20 Endpunkte) für die Buchung zertifizierter Kinderbetreuung, mit E-Mail-OTP-Nutzersitzungen und TOTP-basierter Zwei-Faktor-Authentifizierung für Admins. Regulatorische Geschäftsregeln direkt in die Validierung integriert, mit automatischen .ics-Kalendereinladungen und einer 137-Test-pytest-Suite, per GitHub-Actions-CI/CD auf Docker Compose bereitgestellt.",
    "proj.chatai.title": "Job Scraper und Chat-AI API-Integration",
    "proj.chatai.desc": "Einen Scraper für Stellenbeschreibungen entwickelt, um Daten aus verschiedenen Quellen zu extrahieren, und diesen zur Vergleichung von Lebensläufen in die Chat-AI-API integriert.",
    "proj.flipkart.title": "Flipkart Web-Scraper",
    "proj.flipkart.desc": "Datenabruf-Tool für E-Commerce-Produktdaten — Titel, Preise, Bewertungen, Rezensionen — als CSV exportiert. Entwickelt mit BeautifulSoup und Tkinter UI.",
    "proj.books.title": "Online-Gebrauchtbuchladen",
    "proj.books.desc": "Full-Stack Django-Webanwendung für den Verkauf gebrauchter Bücher mit Nutzerauthentifizierung, Buchsuche, Bestellbewertungen, Session-Management und REST-API-Integration.",
    "skills.label": "// Tech-Stack",
    "skills.heading": "Kenntnisse",
    "skills.cloud": "Cloud &amp; Infrastruktur",
    "skills.languages": "Programmiersprachen",
    "skills.hpc": "HPC &amp; Systeme",
    "skills.data": "Daten &amp; ML-Werkzeuge",
    "skills.devops": "DevOps &amp; CI/CD",
    "skills.web": "Web &amp; Backend",
    "contact.label": "// Kontakt aufnehmen",
    "contact.heading": "Lass uns zusammen<br>arbeiten.",
    "contact.desc": "Offen für Vollzeitstellen in Systems Engineering, Cloud-Infrastruktur oder forschungsnahen Positionen. Wohnhaft in Göttingen — remote möglich.",
    "contact.cta": "E-Mail senden →",
    "footer.text": "Siddharth Simediya — Systemingenieur &amp; Forscher · Göttingen, Deutschland"
  }
};

function setLang(lang) {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang] && translations[lang][key] !== undefined) {
      el.innerHTML = translations[lang][key];
    }
  });
  document.getElementById('btn-en').classList.toggle('active', lang === 'en');
  document.getElementById('btn-de').classList.toggle('active', lang === 'de');
  document.documentElement.lang = lang;
  localStorage.setItem('lang', lang);
}

// Restore saved language preference
(function() {
  const saved = localStorage.getItem('lang');
  if (saved && saved !== 'en') setLang(saved);
})();
